Add change date range tooltip in the Reports view
toggl/mobileapp pull request #7734
Opened 2020-08-21 10:51 UTC by arturs105

## What's this?
This PR adds a brand new shiny tooltip in the reports view ✨ 

### Relationships

Closes #7722 

## Localizations
Will be handled at the end of the project.

## :squid: Permissions
🦑

2020-08-26 14:21 UTC, simonrozsival requested changes
There's one issue I noticed - when you "complete" the onboarding (on the timer page), you can't see the reports tooltip at all. It's maybe related to the predicate comment 👇 - is this gonna be solved later? Is there an issue for that?

2020-08-26 14:21 UTC, simonrozsival commented on Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs
> +                    Observable.Return(true))
Will the predicate observable be implemented later?

2020-09-04 15:00 UTC, arturs105 commented on Toggl.iOS/ViewControllers/ReportsViewController.cs
> +            //    .DisposedBy(DisposeBag);
Nope 🙈

2020-09-11 10:28 UTC, simonrozsival approved these changes

2020-09-11 10:37 UTC, merged