Add red badge to reports tab in Android
toggl/mobileapp pull request #7771
Opened 2020-09-17 11:58 UTC by arturs105

## What's this?
Adds a red badge to reports tab once onboarding is finished

### Relationships

Closes #7720

## :squid: Permissions
🦑

2020-09-21 15:52 UTC, daividssilverio commented
Unrelated, but I got this while testing this run. We might want an issue for that. Not sure if we should show the tooltip bellow the play button or show it at all if we don't have the space for it.
<img width="388" alt="Screen Shot 2020-09-21 at 11 50 07 AM" src="https://user-images.githubusercontent.com/2173493/93790172-bc71de00-fc00-11ea-8a57-8de04d2f84b8.png">

2020-09-21 17:34 UTC, daividssilverio requested changes
Tiny suggestion.
Code looks and works fine already.
Found a small visual issue while testing. The reports adapter also crashes with the same issue I've mentioned [here](https://github.com/toggl/mobileapp/pull/7772#discussion_r492160699).

2020-09-21 17:34 UTC, daividssilverio commented on Toggl.Droid/Activities/MainTabBarActivity.cs
> +                        navigationView.GetOrCreateBadge(navigationView.Menu.GetItem(1).ItemId);
```suggestion
                        navigationView.GetOrCreateBadge(Resource.Id.MainTabReportsItem);
```

2020-09-21 17:34 UTC, daividssilverio commented on Toggl.Droid/Activities/MainTabBarActivity.cs
> +                navigationView.RemoveBadge(navigationView.Menu.GetItem(1).ItemId);
```suggestion
                navigationView.RemoveBadge(Resource.Id.MainTabReportsItem);
```

2020-09-22 09:06 UTC, arturs105 commented
@daividssilverio I know about the reports adapter crashing - it's because i added some new `ReportSomethingElement` for the empty states during iOS development, but i didn't add Android UI counterparts (view holders & layouts). I'm already working on those, so a PR that fixes the crashes will be ready shortly.

2020-09-22 13:32 UTC, daividssilverio approved these changes

2020-09-22 14:27 UTC, merged