Add date range tooltip for Android
toggl/mobileapp pull request #7772
Opened 2020-09-17 19:07 UTC by arturs105

## What's this?
This adds the change date range tooltip in the reports view

### Relationships

Closes #7723

## :squid: Permissions
🦑

2020-09-21 15:07 UTC, daividssilverio commented on Toggl.Droid/Resources/layout/TooltipWithLeftTopArrow.axml
> +<!--        <TextView-->
Is there a reason to leave this commented?
🔥 if not.

2020-09-21 15:27 UTC, daividssilverio commented
I'm getting a tofu in the tooltip on android 6.
![image](https://user-images.githubusercontent.com/2173493/93785808-7d418e00-fbfc-11ea-86a4-fa016fa580d5.png)

That doesn't happen on the main log with
"You've made your first Time Entry on Toggl mobile app 🎉", so I'm guessing we'll be needing another emoji for the reports.

2020-09-21 15:40 UTC, daividssilverio commented on Toggl.Droid/Adapters/ReportsAdapter.cs
> +                ReportProjectsBarChartPlaceholderElement _ => NoData,
The app is crashing on API 29 because of this comparison. Why? Idk... 
It seems that changing the `ReportProjectsBarChartPlaceholderElement`'s `Equals` is enough to fix it.
```cs
public class ReportProjectsBarChartPlaceholderElement : IReportElement
    {
        public bool Equals(IReportElement other)
            => GetType() == other.GetType() 
               && other is ReportProjectsBarChartPlaceholderElement;
    }
```

I'd update `ReportDonutChartPlaceholderIllustrationElement` alongside just in case.

2020-09-21 15:46 UTC, daividssilverio requested changes
Code looks good, it works alright.
The emoji in the tooltip is broken on API 23 and and there's a crash on API 29.
Couldn't test on API 21, the app is crashing in the main log there.

2020-09-29 07:41 UTC, heytherewill approved these changes
Functional test looks good, but please wait for Daivid's review

2020-09-29 07:41 UTC, heytherewill commented on Toggl.Droid/Fragments/ReportsFragment.ViewBinds.cs
> +
```suggestion
```

2020-09-29 13:38 UTC, daividssilverio approved these changes
No tofu anymore!

2020-09-29 16:54 UTC, merged