Add empty states views in Reports for Android
toggl/mobileapp pull request #7779
Opened 2020-09-24 10:22 UTC by arturs105

## What's this?
This adds the final changes to Droid reports from Onboarding 3.0

### Relationships

Closes #7726
Closes #7727

## :squid: Permissions
🦑

2020-09-24 14:55 UTC, daividssilverio requested changes
It works great. Code looks alright.

I'm requesting changes:
- for the static strings you've added to the xmls
- the build configuration changes (revert them if they weren't intentional)

2020-09-24 14:55 UTC, daividssilverio commented on Toggl.Droid/Resources/layout/ReportBarChartPlaceholderElement.axml
> +            android:text="You havent trackd anything yet"
Please add this string to the `Resources.resx` file and add a translation request issue. There's also a typo in `trackd`.

2020-09-24 14:55 UTC, daividssilverio commented on Toggl.Droid/Resources/layout/ReportBarChartPlaceholderElement.axml
> +            android:text="Get tracking!"
Same for this entry

2020-09-24 14:55 UTC, daividssilverio commented on Toggl.Droid/Resources/layout/ReportDonutChartPlaceholderElement.axml
> +            android:text="Here you’ll see a visualization of your Projects containing total clocked hours."
And this one.

2020-09-24 14:55 UTC, daividssilverio commented on Toggl.Droid/Toggl.Droid.csproj
> +    <AndroidSupportedAbis>armeabi-v7a;x86;arm64-v8a;x86_64</AndroidSupportedAbis>
I wouldn't touch these configurations. Was there a reason for that?

2020-09-24 14:55 UTC, daividssilverio commented on Toggl.Droid/Toggl.Droid.csproj
> -    <EmbedAssembliesIntoApk>false</EmbedAssembliesIntoApk>
Same.

2020-09-24 14:55 UTC, daividssilverio commented on Toggl.Droid/Views/BarChartView.cs
> +                    xLabels = new[] {"01/04", "30/04"}.ToImmutableList();
Just my two cents, but can't we use something more placeholder-y? This could be confusing. Maybe "dd/MM" or something like the actual currently selected date range.

2020-09-25 11:09 UTC, arturs105 commented on Toggl.Droid/Views/BarChartView.cs
> +                    xLabels = new[] {"01/04", "30/04"}.ToImmutableList();
Using the actual dates would be too much work, i think, and using `dd/MM` might be even more confusing than these hardcoded strings.

2020-09-25 13:09 UTC, daividssilverio commented on Toggl.Droid/Views/BarChartView.cs
> +                    xLabels = new[] {"01/04", "30/04"}.ToImmutableList();
fair enough

2020-09-25 13:19 UTC, daividssilverio requested changes
You left the changes in `AndroidSupportedAbis` for the release builds. Please revert unless there's a reason for them. Otherwise, looks good to me.

2020-09-25 17:26 UTC, daividssilverio approved these changes
:shipit:

2020-09-28 08:48 UTC, merged